# Markdown Snippets (Rewritten)

[[snippets]]
prefix = "h1"
scope = ["markdown"]
body = '''
# ${1:Heading 1}
'''
description = "Insert a level 1 header"

[[snippets]]
prefix = "h2"
scope = ["markdown"]
body = '''
## ${1:Heading 2}
'''
description = "Insert a level 2 header"

[[snippets]]
prefix = "h3"
scope = ["markdown"]
body = '''
### ${1:Heading 3}
'''
description = "Insert a level 3 header"

[[snippets]]
prefix = "h4"
scope = ["markdown"]
body = '''
#### ${1:Heading 4}
'''
description = "Insert a level 4 header"

[[snippets]]
prefix = "h5"
scope = ["markdown"]
body = '''
##### ${1:Heading 5}
'''
description = "Insert a level 5 header"

[[snippets]]
prefix = "h6"
scope = ["markdown"]
body = '''
###### ${1:Heading 6}
'''
description = "Insert a level 6 header"

[[snippets]]
prefix = "l"
scope = ["markdown"]
body = '''
[${1:Link Text}](${2:URL})
'''
description = "Insert a hyperlink"

[[snippets]]
prefix = "link"
scope = ["markdown"]
body = '''
[${1:Link Text}](${2:URL})
'''
description = "Insert a hyperlink"

[[snippets]]
prefix = "u"
scope = ["markdown"]
body = '''
<${1:URL}>
'''
description = "Insert a plain URL"

[[snippets]]
prefix = "url"
scope = ["markdown"]
body = '''
<${1:URL}>
'''
description = "Insert a plain URL"

[[snippets]]
prefix = "img"
scope = ["markdown"]
body = '''
![${1:Alt Text}](${2:Path})
'''
description = "Insert an image"

[[snippets]]
prefix = "strikethrough"
scope = ["markdown"]
body = '''
~~${1:Text}~~
'''
description = "Insert text with strikethrough"

[[snippets]]
prefix = "b"
scope = ["markdown"]
body = '''
**${1:Bold Text}**
'''
description = "Insert bold text"

[[snippets]]
prefix = "bold"
scope = ["markdown"]
body = '''
**${1:Bold Text}**
'''
description = "Insert bold text"

[[snippets]]
prefix = "i"
scope = ["markdown"]
body = '''
*${1:Italic Text}*
'''
description = "Insert italic text"

[[snippets]]
prefix = "italic"
scope = ["markdown"]
body = '''
*${1:Italic Text}*
'''
description = "Insert italic text"

[[snippets]]
prefix = "bi"
scope = ["markdown"]
body = '''
***${1:Bold and Italic Text}***
'''
description = "Insert bold and italic text"

[[snippets]]
prefix = "bold_italic"
scope = ["markdown"]
body = '''
***${1:Bold and Italic Text}***
'''
description = "Insert bold and italic text"

[[snippets]]
prefix = "quote"
scope = ["markdown"]
body = '''
> ${1:Quoted Text}
'''
description = "Insert a blockquote"

[[snippets]]
prefix = "code"
scope = ["markdown"]
body = '''
`${1}` ${0}
'''
description = "Insert code"

[[snippets]]
prefix = "codeblock"
scope = ["markdown"]
body = '''
```${1:language}
${0}
```
'''
description = "Insert a code block"

[[snippets]]
prefix = "ul"
scope = ["markdown"]
body = '''
- ${1:First Item}
- ${2:Second Item}
- ${3:Third Item}
'''
description = "Insert an unordered list"

[[snippets]]
prefix = "unordered_list"
scope = ["markdown"]
body = '''
- ${1:First Item}
- ${2:Second Item}
- ${3:Third Item}
'''
description = "Insert an unordered list"

[[snippets]]
prefix = "ol"
scope = ["markdown"]
body = '''
1. ${1:First Item}
2. ${2:Second Item}
3. ${3:Third Item}
'''
description = "Insert an ordered list"

[[snippets]]
prefix = "ordered_list"
scope = ["markdown"]
body = '''
1. ${1:First Item}
2. ${2:Second Item}
3. ${3:Third Item}
'''
description = "Insert an ordered list"

[[snippets]]
prefix = "hrl"
scope = ["markdown"]
body = '''
---
'''
description = "Insert a horizontal rule"

[[snippets]]
prefix = "horizontal_rule"
scope = ["markdown"]
body = '''
---
'''
description = "Insert a horizontal rule"

[[snippets]]
prefix = "task"
scope = ["markdown"]
body = '''
- [${1| ,x|}] ${2:Task 1}
'''
description = "Insert a single task list item"

[[snippets]]
prefix = "task2"
scope = ["markdown"]
body = '''
- [${1| ,x|}] ${2:Task 1}
- [${3| ,x|}] ${4:Task 2}
'''
description = "Insert a task list with two items"

[[snippets]]
prefix = "task3"
scope = ["markdown"]
body = '''
- [${1| ,x|}] ${2:Task 1}
- [${3| ,x|}] ${4:Task 2}
- [${5| ,x|}] ${6:Task 3}
'''
description = "Insert a task list with three items"

# Callouts
[[snippets]]
prefix = "note"
scope = ["markdown"]
body = '''
> [!NOTE]
> ${1:Note content}
'''
description = "Insert a note block"

[[snippets]]
prefix = "tip"
scope = ["markdown"]
body = '''
> [!TIP]
> ${1:Tip content}
'''
description = "Insert a tip block"

[[snippets]]
prefix = "important"
scope = ["markdown"]
body = '''
> [!IMPORTANT]
> ${1:Important content}
'''
description = "Insert an important block"

[[snippets]]
prefix = "warning"
scope = ["markdown"]
body = '''
> [!WARNING]
> ${1:Warning content}
'''
description = "Insert a warning block"

[[snippets]]
prefix = "caution"
scope = ["markdown"]
body = '''
> [!CAUTION]
> ${1:Caution content}
'''
description = "Insert a caution block"

# >>> Tables <<<
[[snippets]]
prefix = "table"
scope = ["markdown"]
body = '''
| ${1:Column 1} | ${2:Column 2} | ${3:Column 3} |
|--------------|--------------|--------------|
| ${4:Row 1}   | ${5:Row 1}   | ${6:Row 1}   |
'''
description = "Insert a table with three columns and one row"

# Markdown Table Snippets

[[snippets]]
prefix = "2x1table"
scope = ["markdown"]
body = '''
| ${1:Column1} |
| ------------- |
| ${2:Item1} |
${0}
'''
description = "Insert table with 2 rows and 1 column. First row is heading."

[[snippets]]
prefix = "3x1table"
scope = ["markdown"]
body = '''
| ${1:Column1} |
| ------------- |
| ${2:Item1} |
| ${3:Item2} |
${0}
'''
description = "Insert table with 3 rows and 1 column. First row is heading."

[[snippets]]
prefix = "4x1table"
scope = ["markdown"]
body = '''
| ${1:Column1} |
| ------------- |
| ${2:Item1} |
| ${3:Item2} |
| ${4:Item3} |
${0}
'''
description = "Insert table with 4 rows and 1 column. First row is heading."

[[snippets]]
prefix = "5x1table"
scope = ["markdown"]
body = '''
| ${1:Column1} |
| ------------- |
| ${2:Item1} |
| ${3:Item2} |
| ${4:Item3} |
| ${5:Item4} |
${0}
'''
description = "Insert table with 5 rows and 1 column. First row is heading."

[[snippets]]
prefix = "2x2table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} |
| -------------- | --------------- |
| ${3:Item1.1} | ${4:Item2.1} |
${0}
'''
description = "Insert table with 2 rows and 2 columns. First row is heading."

[[snippets]]
prefix = "3x2table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} |
| -------------- | --------------- |
| ${3:Item1.1} | ${4:Item2.1} |
| ${5:Item1.2} | ${6:Item2.2} |
${0}
'''
description = "Insert table with 3 rows and 2 columns. First row is heading."

[[snippets]]
prefix = "4x2table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} |
| -------------- | --------------- |
| ${3:Item1.1} | ${4:Item2.1} |
| ${5:Item1.2} | ${6:Item2.2} |
| ${7:Item1.3} | ${8:Item2.3} |
${0}
'''
description = "Insert table with 4 rows and 2 columns. First row is heading."

[[snippets]]
prefix = "5x2table"
scope = ["markdown"]
body = '''
| ${1:Column1}   | ${2:Column2}    |
| --------------- | --------------- |
| ${3:Item1.1}   | ${4:Item2.1}   |
| ${5:Item1.2}   | ${6:Item2.2}   |
| ${7:Item1.3}   | ${8:Item2.3}   |
| ${9:Item1.4}   | ${10:Item2.4}   |
${0}
'''
description = "Insert table with 5 rows and 2 columns. First row is heading."

[[snippets]]
prefix = "2x3table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} | ${3:Column3} |
| --------------- | --------------- | --------------- |
| ${4:Item1.1} | ${5:Item2.1} | ${6:Item3.1} |
${0}
'''
description = "Insert table with 2 rows and 3 columns. First row is heading."

[[snippets]]
prefix = "3x3table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} | ${3:Column3} |
| --------------- | --------------- | --------------- |
| ${4:Item1.1} | ${5:Item2.1} | ${6:Item3.1} |
| ${7:Item1.2} | ${8:Item2.2} | ${9:Item3.2} |
${0}
'''
description = "Insert table with 3 rows and 3 columns. First row is heading."

[[snippets]]
prefix = "4x3table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} | ${3:Column3} |
| --------------- | --------------- | --------------- |
| ${4:Item1.1} | ${5:Item2.1} | ${6:Item3.1} |
| ${7:Item1.2} | ${8:Item2.2} | ${9:Item3.2} |
| ${10:Item1.3} | ${11:Item2.3} | ${12:Item3.3} |
${0}
'''
description = "Insert table with 4 rows and 3 columns. First row is heading."

[[snippets]]
prefix = "5x3table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} | ${3:Column3} |
| --------------- | --------------- | --------------- |
| ${4:Item1.1} | ${5:Item2.1} | ${6:Item3.1} |
| ${7:Item1.2} | ${8:Item2.2} | ${9:Item3.2} |
| ${10:Item1.3} | ${11:Item2.3} | ${12:Item3.3} |
| ${13:Item1.4} | ${14:Item2.4} | ${15:Item3.4} |
${0}
'''
description = "Insert table with 5 rows and 3 columns. First row is heading."

[[snippets]]
prefix = "2x4table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} | ${3:Column3} | ${4:Column4} |
| --------------- | --------------- | --------------- | --------------- |
| ${5:Item1.1} | ${6:Item2.1} | ${7:Item3.1} | ${8:Item4.1} |
${0}
'''
description = "Insert table with 2 rows and 4 columns. First row is heading."

[[snippets]]
prefix = "3x4table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} | ${3:Column3} | ${4:Column4} |
| --------------- | --------------- | --------------- | --------------- |
| ${5:Item1.1} | ${6:Item2.1} | ${7:Item3.1} | ${8:Item4.1} |
| ${9:Item1.2} | ${10:Item2.2} | ${11:Item3.2} | ${12:Item4.2} |
${0}
'''
description = "Insert table with 3 rows and 4 columns. First row is heading."

[[snippets]]
prefix = "4x4table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} | ${3:Column3} | ${4:Column4} |
| --------------- | --------------- | --------------- | --------------- |
| ${5:Item1.1} | ${6:Item2.1} | ${7:Item3.1} | ${8:Item4.1} |
| ${9:Item1.2} | ${10:Item2.2} | ${11:Item3.2} | ${12:Item4.2} |
| ${13:Item1.3} | ${14:Item2.3} | ${15:Item3.3} | ${16:Item4.3} |
${0}
'''
description = "Insert table with 4 rows and 4 columns. First row is heading."

[[snippets]]
prefix = "5x4table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} | ${3:Column3} | ${4:Column4} |
| --------------- | --------------- | --------------- | --------------- |
| ${5:Item1.1} | ${6:Item2.1} | ${7:Item3.1} | ${8:Item4.1} |
| ${9:Item1.2} | ${10:Item2.2} | ${11:Item3.2} | ${12:Item4.2} |
| ${13:Item1.3} | ${14:Item2.3} | ${15:Item3.3} | ${16:Item4.3} |
| ${17:Item1.4} | ${18:Item2.4} | ${19:Item3.4} | ${20:Item4.4} |
${0}
'''
description = "Insert table with 5 rows and 4 columns. First row is heading."

[[snippets]]
prefix = "2x5table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} | ${3:Column3} | ${4:Column4} | ${5:Column5} |
| --------------- | --------------- | --------------- | --------------- | --------------- |
| ${6:Item1.1} | ${7:Item2.1} | ${8:Item3.1} | ${9:Item4.1} | ${10:Item5.1} |
${0}
'''
description = "Insert table with 2 rows and 5 columns. First row is heading."

[[snippets]]
prefix = "3x5table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} | ${3:Column3} | ${4:Column4} | ${5:Column5} |
| --------------- | --------------- | --------------- | --------------- | --------------- |
| ${6:Item1.1} | ${7:Item2.1} | ${8:Item3.1} | ${9:Item4.1} | ${10:Item5.1} |
| ${11:Item1.2} | ${12:Item2.2} | ${13:Item3.2} | ${14:Item4.2} | ${15:Item5.2} |
${0}
'''
description = "Insert table with 3 rows and 5 columns. First row is heading."

[[snippets]]
prefix = "4x5table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} | ${3:Column3} | ${4:Column4} | ${5:Column5} |
| --------------- | --------------- | --------------- | --------------- | --------------- |
| ${6:Item1.1} | ${7:Item2.1} | ${8:Item3.1} | ${9:Item4.1} | ${10:Item5.1} |
| ${11:Item1.2} | ${12:Item2.2} | ${13:Item3.2} | ${14:Item4.2} | ${15:Item5.2} |
| ${16:Item1.3} | ${17:Item2.3} | ${18:Item3.3} | ${19:Item4.3} | ${20:Item5.3} |
${0}
'''
description = "Insert table with 4 rows and 5 columns. First row is heading."

[[snippets]]
prefix = "5x5table"
scope = ["markdown"]
body = '''
| ${1:Column1} | ${2:Column2} | ${3:Column3} | ${4:Column4} | ${5:Column5} |
| --------------- | --------------- | --------------- | --------------- | --------------- |
| ${6:Item1.1} | ${7:Item2.1} | ${8:Item3.1} | ${9:Item4.1} | ${10:Item5.1} |
| ${11:Item1.2} | ${12:Item2.2} | ${13:Item3.2} | ${14:Item4.2} | ${15:Item5.2} |
| ${16:Item1.3} | ${17:Item2.3} | ${18:Item3.3} | ${19:Item4.3} | ${20:Item5.3} |
| ${21:Item1.4} | ${22:Item2.4} | ${23:Item3.4} | ${24:Item4.4} | ${25:Item5.4} |
${0}
'''
description = "Insert table with 5 rows and 5 columns. First row is heading."
